### ISSUE TITLE
Details of SGCN

### ISSUE THREAD

**Issue by mrzhang11** [cyvius96/adgpm#10]
Thanks for your contributions on this work, but I have some questions about SGCN.

In the paper, it mentions that "As DGP, our SGCN model makes use of the proposed two-stage finetuning approach", but did it use the descendant and ancestor patterns and weighting schema, like DGP as well? 

From the code, it seems that SGCN is very similar to GCNZ. Their differences mainly are the number of hidden layers, training epochs and implementation details, is it corret?

Thanks very much!

**Comment by yinboc** [comment]
Thanks for your question.

Yes, SGCN is a single-hidden-layer GCN with finetuning, you can check the appendix in our paper for ablation studies.

**Comment by mrzhang11** [comment]
Okay, thanks for your quick reply!
