### ISSUE TITLE
ImportError: No module named nltk.corpus

### ISSUE THREAD

**Issue by joanconquerlee** [cyvius96/adgpm#11]
root@aca4066e21cd:/tmp/pycharm_project_546/materials# python make_induced_graph.py
Traceback (most recent call last):
  File "make_induced_graph.py", line 4, in <module>
    from nltk.corpus import wordnet as wn
ImportError: No module named nltk.corpus

**Comment by yinboc** [comment]
Hi, you need https://www.nltk.org/.

Best
