### ISSUE TITLE
How to get "2-hops", "3-hops" and "all-hops" test dataset

### ISSUE THREAD

**Issue by kaiqiangh** [cyvius96/adgpm#12]
Hi, thanks for sharing codes. I tried to get "2-hops", "3-hops" and "all-hops" dataset (I followed this repo https://github.com/JudyYe/zero-shot-gcn/blob/master/DATASET.md), but most of URLs in ImageNet are not valid right now. I only can download ImageNet 2012 as whole (120 GB). Any tips for that? Thanks

**Comment by kaiqiangh** [comment]
Do I need these datasets to conduct experiments in this repo?

**Comment by yinboc** [comment]
Do you mean ImageNet 21K dataset? You may search "imagenet fall 2011 release" for that.

This dataset is used for evaluation.

Best,

**Comment by kaiqiangh** [comment]
Thanks for your reply. 
I found two tables in your paper, which show Top-k accuracy for different models. In the first table, the test sets are "2-hops", "3-hops" and 'all'. Do these test sets come from "imagenet fall 2011 release"? Also, in the second table, the test sets are "2-hops+1k", "3-hops+1k" and "all+1k". Does "1K" dataset refer to ImageNet 2012 dataset? 
By the way, for downloading "imagenet fall 2011 release", I cannot download it in ImageNet page as it displays "URL is not valid". Do you know another website that allows me to download it? 
Thanks a million.

**Comment by yinboc** [comment]
Yes. 1K is ILSVRC 2012, while "k-hops" are from ImageNet fall 2011.

I searched "imagenet fall 2011" in Google and found:
http://academictorrents.com/details/564a77c1e1119da199ff32622a1609431b9f1c47/tech&dllist=1

This seems to be the same dataset as in our paper's.

Thanks for your interest in our work!

**Comment by kaiqiangh** [comment]
Thank you so much! I gonna try this link. Hope I can get it.

**Comment by kaiqiangh** [comment]
Unfortunately, this link does not work as well. I will try to find other ways to download. Thanks for that.

**Comment by yinboc** [comment]
> Unfortunately, this link does not work as well. I will try to find other ways to download. Thanks for that.

Ok, good luck!

**Comment by flash1803** [comment]
> Unfortunately, this link does not work as well. I will try to find other ways to download. Thanks for that.

Did you get the available link? How do you solve this problem?

**Comment by yinboc** [comment]
That link worked for me, did you have trouble using that link?

**Comment by flash1803** [comment]
> That link worked for me, did you have trouble using that link?

Yes, actually I download the torrent, but the torrent doesn't really work.

**Comment by yinboc** [comment]
I see, it seems the torrent has some issues in recent months.

Did you try this? https://github.com/JudyYe/zero-shot-gcn/blob/master/DATASET.md

**Comment by flash1803** [comment]
Yes. I have registered at "http://www.image-net.org/" using my edu email and submitted a request for the original images like a month ago. But never get the approval for that.

**Comment by yinboc** [comment]
Maybe you can email them.

I will reply here when I found another way for downloading it.

**Comment by flash1803** [comment]
Ok, thank you. No offence, is it possible for you to share the dataset with my lab?

**Comment by yinboc** [comment]
Unfortunately I don't have the dataset currently, it was in an old server which I don't have access now.

**Comment by flash1803** [comment]
Thank you.

**Comment by yinboc** [comment]
You are welcome. Thanks for your interest in our work.

**Comment by flash1803** [comment]
> Maybe you can email them.
> 
> I will reply here when I found another way for downloading it.

The torrent somehow is working now. I think it'll be fine.

**Comment by yinboc** [comment]
That's great. :D
