### ISSUE TITLE
Time of your train stage

### ISSUE THREAD

**Issue by zgyangleo** [cyvius96/adgpm#14]
in your paper, your model is trained for 3000 epochs, how much time do you spend in it

**Comment by yinboc** [comment]
I remember it takes a few hours for the first stage training (i.e. training graph network). How long do you spend for training by running the code?

**Comment by zgyangleo** [comment]
i didn't train on it. i thought the training 3000 epochs would be long.

**Comment by yinboc** [comment]
It will not be too long. :D

**Comment by Max-Fu** [comment]
A follow-up question: how long does the finetuning (20 epochs) take? I am at epoch 11 now and it took me about a day. Does that sound right to you?
