### ISSUE TITLE
About Result

### ISSUE THREAD

**Issue by lil-wayne-0319** [cyvius96/adgpm#20]
Thank you very much for your contribution!
I have tested your codes with default settings(with finetuning), and the best preformance on imageNet(2-hops) is 25.49%/25.82%(SGCN/DGP).
It seems there is a little degradation with your paper(26.2%/26.6% for SGCN/DGP).Do I miss something or you have some other tricks?
I find that one tenth of the pictures were randomly picked in 'evaluate_imagenet.py'. Maybe that's the reason?
By the way, I'll be very appriciate it if you can provide the 'best.pred'.
Thank you!

**Comment by GermeauSimon** [comment]
I have the same? Did you get a response?
