### ISSUE TITLE
What‘s the difference between GPM and GCNZ with few layer

### ISSUE THREAD

**Issue by Wangt-CN** [cyvius96/adgpm#4]
Hi,

It's a great work, but i have some confusions about GPM and GCNZ.

From the reported result in paper, GPM has already received a huge improvement compared to the SOTA method GCNZ, however the paper just said GPM only use single layer compared to GNCZ.

However in GNCZ, author's experiment indicate that addition layers bring the improvement results. So i'm very confused.

Can i ask more clear difference between GPM and GCNZ?

Thanks very much!

**Comment by yinboc** [comment]
Thanks for the question.

The main differences are: 1. number of hidden channels 2. training epochs
Both contribute much improvement to GCNZ-1.

1:
GPM: 2048
GNCZ-1: 512 
GNCZ-6: 2048, 2048, 1024, 1024, 512

2:
GPM 3000 epochs, GNCZ 300 epochs

**Comment by Wangt-CN** [comment]
Great and that's clear！Thank you for your reply!
