### ISSUE TITLE
What does imagenet-xml-wnids.json come from?

### ISSUE THREAD

**Issue by D-X-Y** [cyvius96/adgpm#8]
Hi,

I noticed that there is a "imagenet-xml-wnids.json" file used in `make_induced_graph.py`.
Would you mind to let me where does it come from and what is it used for?

Best Regards,

**Comment by yinboc** [comment]
Hi,

It is the wnids (WordNet IDs of classes) in this [http://www.image-net.org/api/xml/structure_released.xml](xml file), which could be found in http://image-net.org/download-API.

We used these wnids together with the 21K wnids (these two sets overlap for most nodes) as the nodes of knowledge graph, in order to be consistent with previous works.

**Comment by D-X-Y** [comment]
Thanks for your instant response.
Would you mind to let me what is the purpose of this line "https://github.com/cyvius96/DGP/blob/master/materials/make_induced_graph.py#L64"?
It seems that the induce_parents function does not add any node in the list "s". If you are using the nodes from imagenet-xml-wnids.json with 21K wnids. Only https://github.com/cyvius96/DGP/blob/master/materials/make_induced_graph.py#L66 to https://github.com/cyvius96/DGP/blob/master/materials/make_induced_graph.py#L69 is enough to include all these nodes?

**Comment by yinboc** [comment]
In induce_parents(s, stop_set), s is assigned to q and elements are appended to q, so s (type: list) will also be modified. The idea of induce_parents is to attach 21K-nodes to xml-nodes, some intermediate nodes might be added also.

**Comment by D-X-Y** [comment]
Yes, but it seems this line has never been True : "https://github.com/cyvius96/DGP/blob/master/materials/make_induced_graph.py#L40". I also checked the length of s before and after the induce_parents function. Their lengths are the same.

**Comment by yinboc** [comment]
Yes, I just checked the code and I found that line is always False, which means all 21K-nodes are already attached to those xml-nodes and no additional nodes are needed.

Thanks for your observation.

**Comment by D-X-Y** [comment]
You are welcome~
