### ISSUE TITLE
Dataset splits for awa2

### ISSUE THREAD

**Issue by liulu112601** [cyvius96/adgpm#9]
Hi,

Thanks for the release of your code, which gives me a lot of references in zero-shot learning literature.

I found that the dataset split in the awa2-split.json file in this repo is different from the split shown on the awa2 dataset website: https://cvml.ist.ac.at/AwA2/.

Can I ask if you use different splits and if so why you use different splits?

**Comment by yinboc** [comment]
Hi,

Thanks for your interest in our work.

The file awa2-split.json should be the "proposed split" in AwA2, which ensures that there is no overlap between the test classes and the ImageNet 2012 dataset.

**Comment by liulu112601** [comment]
Thx for the instant response. That's correct.
